// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendingMachine.Data;

#nullable disable

namespace VendingMachine.Migrations
{
    [DbContext(typeof(VendingMachineContext))]
    [Migration("20220323190958_updateData")]
    partial class updateData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VendingMachine.Entities.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Address = "กรุงเทพ"
                        },
                        new
                        {
                            Id = "2",
                            Address = "ปทุมธานี"
                        },
                        new
                        {
                            Id = "3",
                            Address = "พระรามสาม"
                        });
                });

            modelBuilder.Entity("VendingMachine.Entities.Machine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            LocationId = "1",
                            Name = "M1"
                        },
                        new
                        {
                            Id = "2",
                            LocationId = "1",
                            Name = "M2"
                        },
                        new
                        {
                            Id = "3",
                            LocationId = "2",
                            Name = "C1"
                        },
                        new
                        {
                            Id = "4",
                            LocationId = "3",
                            Name = "C2"
                        },
                        new
                        {
                            Id = "5",
                            LocationId = "3",
                            Name = "C2"
                        });
                });

            modelBuilder.Entity("VendingMachine.Entities.MachineInventory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("MachineId")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductId");

                    b.ToTable("MachineInventory");

                    b.HasData(
                        new
                        {
                            Id = "aa1dbef8-977d-4e29-a285-d32314185afb",
                            MachineId = "1",
                            ProductId = "P1",
                            Quality = 12
                        },
                        new
                        {
                            Id = "4b3c9958-09b7-4ef7-9b09-28f340343f1b",
                            MachineId = "1",
                            ProductId = "P2",
                            Quality = 10
                        },
                        new
                        {
                            Id = "b7d698db-ab1a-46fe-af66-939ecd33cdad",
                            MachineId = "1",
                            ProductId = "C1",
                            Quality = 20
                        },
                        new
                        {
                            Id = "2e77c93d-ff01-45ad-888d-19fff21a0b6f",
                            MachineId = "1",
                            ProductId = "C2",
                            Quality = 14
                        },
                        new
                        {
                            Id = "05a9b2b2-aa8c-450f-a673-0d6ff5b25348",
                            MachineId = "2",
                            ProductId = "C2",
                            Quality = 11
                        },
                        new
                        {
                            Id = "931ecc20-4981-4ea4-856f-536c5e104a77",
                            MachineId = "3",
                            ProductId = "C1",
                            Quality = 11
                        },
                        new
                        {
                            Id = "a9b52ca4-a324-4b34-bf20-0a5188b6e1e5",
                            MachineId = "3",
                            ProductId = "P1",
                            Quality = 10
                        },
                        new
                        {
                            Id = "a5ea28d6-2b26-483e-989b-037b5044b2b8",
                            MachineId = "4",
                            ProductId = "P1",
                            Quality = 12
                        });
                });

            modelBuilder.Entity("VendingMachine.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "P1",
                            Name = "Coke",
                            Price = 20.0
                        },
                        new
                        {
                            Id = "P2",
                            Name = "Pepsi",
                            Price = 10.0
                        },
                        new
                        {
                            Id = "C1",
                            Name = "Coffee",
                            Price = 60.0
                        },
                        new
                        {
                            Id = "C2",
                            Name = "Beer",
                            Price = 100.0
                        });
                });

            modelBuilder.Entity("VendingMachine.Entities.Machine", b =>
                {
                    b.HasOne("VendingMachine.Entities.Location", "Location")
                        .WithMany("Machines")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("VendingMachine.Entities.MachineInventory", b =>
                {
                    b.HasOne("VendingMachine.Entities.Machine", "Machine")
                        .WithMany("MachineInventories")
                        .HasForeignKey("MachineId");

                    b.HasOne("VendingMachine.Entities.Product", "Product")
                        .WithMany("MachineInventories")
                        .HasForeignKey("ProductId");

                    b.Navigation("Machine");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VendingMachine.Entities.Location", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("VendingMachine.Entities.Machine", b =>
                {
                    b.Navigation("MachineInventories");
                });

            modelBuilder.Entity("VendingMachine.Entities.Product", b =>
                {
                    b.Navigation("MachineInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
